# **AI Techniques and Tools Subject**

> Version corrigée : notebook `.ipynb` valide, sorties HTML supprimées pour éviter les problèmes d’affichage. Exécutez les cellules après avoir placé `cars.csv` dans le bon dossier ou après avoir monté Google Drive.






Axis 3: Research and analysis of data driven by AI (24 hours)

Axis III focuses on data acquisition, processing, and analysis using artificial intelligence (AI) tools. The objective is to master the fundamental steps of modeling and interpreting results through modern mathematical and algorithmic approaches.

## 1-	Introduction to Data Science with Python (2 hours)
- **Objective:** Establish the technical foundations of data science with Python. Explore fundamental libraries, understand data structures, and master the basic exploration and inspection commands.
- **Tools:** *Jupyter Notebook, Google Colab, Python 3.8+, Pandas, NumPy*
- **Tools:** *Data loading CSV, Excel, JSON*)

In [3]:
# import libraries
from pathlib import Path
import pandas as pd

In [4]:
# Load CSV file
csv_name = 'cars.csv'

try:
    from google.colab import drive
    drive.mount('/content/drive')
except Exception:
    pass

search_roots = [Path('.'), Path('/content/drive/MyDrive')]
candidates = []
for root in search_roots:
    if root.exists():
        candidates.extend(root.rglob(csv_name))

if not candidates:
    raise FileNotFoundError(f"{csv_name} not found. Put it in the notebook folder or in Google Drive.")

csv_path = candidates[0]
print(f"CSV loaded from: {csv_path}")

df_csv = pd.read_csv(csv_path)
df = df_csv.copy()

CSV loaded from: cars.csv

- **DataFrame Overview**

In [5]:
df.head() 	# first 5 lines

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [6]:
df.tail() 	# last 5 lines

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price
15406,19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [7]:
df.sample(3) 	# 3 random lines

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price
10716,13643,Mercedes-Benz C-Class,Mercedes-Benz,C-Class,8,39000,Dealer,Diesel,Automatic,19.27,2143,170.0,5,1349000
12840,16284,Maruti Alto,Maruti,Alto,3,20000,Individual,Petrol,Manual,24.70,796,47.3,5,280000
8453,10866,Ford Figo,Ford,Figo,9,50000,Individual,Diesel,Manual,20.00,1399,68.0,5,240000

In [8]:
df.shape 	# dimensions (rows, columns)

(15411, 14)

In [9]:
df.columns 	# column names

Index(['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
       'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
       'max_power', 'seats', 'price'],
      dtype='object')

In [10]:
print(df.columns) #same with print

Index(['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
       'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
       'max_power', 'seats', 'price'],
      dtype='object')

In [11]:
df.dtypes 	# types of each column

Unnamed: 0             int64
car_name              object
brand                 object
model                 object
vehicle_age            int64
km_driven              int64
seller_type           object
fuel_type             object
transmission_type     object
mileage              float64
engine                 int64
max_power            float64
seats                  int64
price                  int64
dtype: object

In [12]:
df.info() 	# full summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  price              15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

- **Basic Statistics**

In [13]:
df.describe() # numerical statistical summary

,Unnamed: 0,vehicle_age,km_driven,mileage,engine,max_power,seats,price
count,15411.000000,15411.000000,1.541100e+04,15411.000000,15411.000000,15411.000000,15411.000000,1.541100e+04
mean,9811.857699,6.036338,5.561648e+04,19.701151,1486.057751,100.588254,5.325482,7.749711e+05
std,5643.418542,3.013291,5.161855e+04,4.171265,521.106696,42.972979,0.807628,8.941284e+05
min,0.000000,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,4.000000e+04
25%,4906.500000,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,9872.000000,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.560000e+05
75%,14668.500000,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,19543.000000,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

In [14]:
df.describe().round(2) #Round all numerical statistics in the summary to 2 decimal places for better readability

,Unnamed: 0,vehicle_age,km_driven,mileage,engine,max_power,seats,price
count,15411.00,15411.00,15411.00,15411.00,15411.00,15411.00,15411.00,15411.00
mean,9811.86,6.04,55616.48,19.70,1486.06,100.59,5.33,774971.12
std,5643.42,3.01,51618.55,4.17,521.11,42.97,0.81,894128.36
min,0.00,0.00,100.00,4.00,793.00,38.40,0.00,40000.00
25%,4906.50,4.00,30000.00,17.00,1197.00,74.00,5.00,385000.00
50%,9872.00,6.00,50000.00,19.67,1248.00,88.50,5.00,556000.00
75%,14668.50,8.00,70000.00,22.70,1582.00,117.30,5.00,825000.00
max,19543.00,29.00,3800000.00,33.54,6592.00,626.00,9.00,39500000.00

In [15]:
df['brand'].value_counts() 	# frequency of values

Maruti           4992
Hyundai          2982
Honda            1485
Mahindra         1011
Toyota            793
Ford              790
Volkswagen        620
Renault           536
BMW               439
Tata              430
Mercedes-Benz     337
Skoda             334
Audi              192
Datsun            170
Jaguar             59
Land Rover         51
Jeep               41
Kia                32
Porsche            21
Volvo              20
MG                 19
Mini               17
Nissan             11
Lexus              10
Isuzu               8
Bentley             3
Maserati            2
ISUZU               2
Ferrari             1
Mercedes-AMG        1
Rolls-Royce         1
Force               1
Name: brand, dtype: int64

In [16]:
df ['brand'].nunique() 	# number of unique values

32

- **Display configuration**

In [17]:
pd.set_option('display.max_columns',None) # display all columns

print(df)

       Unnamed: 0         car_name     brand     model  vehicle_age  \
0               0      Maruti Alto    Maruti      Alto            9
1               1    Hyundai Grand   Hyundai     Grand            5
2               2      Hyundai i20   Hyundai       i20           11
3               3      Maruti Alto    Maruti      Alto            9
4               4    Ford Ecosport      Ford  Ecosport            6
...           ...              ...       ...       ...          ...
15406       19537      Hyundai i10   Hyundai       i10            9
15407       19540    Maruti Ertiga    Maruti    Ertiga            2
15408       19541      Skoda Rapid     Skoda     Rapid            6
15409       19542  Mahindra XUV500  Mahindra    XUV500            5
15410       19543       Honda City     Honda      City            2

       km_driven seller_type fuel_type transmission_type  mileage  engine  \
0         120000  Individual    Petrol            Manual    19.70     796
1          20000  Individual    Petrol            Manual    18.90    1197
2          60000  Individual    Petrol            Manual    17.00    1197
3          37000  Individual    Petrol            Manual    20.92     998
4          30000      Dealer    Diesel            Manual    22.77    1498
...          ...         ...       ...               ...      ...     ...
15406      10723      Dealer    Petrol            Manual    19.81    1086
15407      18000      Dealer    Petrol            Manual    17.50    1373
15408      67000      Dealer    Diesel            Manual    21.14    1498
15409    3800000      Dealer    Diesel            Manual    16.00    2179
15410      13000      Dealer    Petrol         Automatic    18.00    1497

       max_power  seats    price
0          46.30      5   120000
1          82.00      5   550000
2          80.00      5   215000
3          67.10      5   226000
4          98.59      5   570000
...          ...    ...      ...
15406      68.05      5   250000
15407      91.10      7   925000
15408     103.52      5   425000
15409     140.00      7  1225000
15410     117.60      5  1200000

[15411 rows x 14 columns]

In [18]:
pd.set_option('display.precision',2) # number of decimal places

print(df)

       Unnamed: 0         car_name     brand     model  vehicle_age  \
0               0      Maruti Alto    Maruti      Alto            9
1               1    Hyundai Grand   Hyundai     Grand            5
2               2      Hyundai i20   Hyundai       i20           11
3               3      Maruti Alto    Maruti      Alto            9
4               4    Ford Ecosport      Ford  Ecosport            6
...           ...              ...       ...       ...          ...
15406       19537      Hyundai i10   Hyundai       i10            9
15407       19540    Maruti Ertiga    Maruti    Ertiga            2
15408       19541      Skoda Rapid     Skoda     Rapid            6
15409       19542  Mahindra XUV500  Mahindra    XUV500            5
15410       19543       Honda City     Honda      City            2

       km_driven seller_type fuel_type transmission_type  mileage  engine  \
0         120000  Individual    Petrol            Manual    19.70     796
1          20000  Individual    Petrol            Manual    18.90    1197
2          60000  Individual    Petrol            Manual    17.00    1197
3          37000  Individual    Petrol            Manual    20.92     998
4          30000      Dealer    Diesel            Manual    22.77    1498
...          ...         ...       ...               ...      ...     ...
15406      10723      Dealer    Petrol            Manual    19.81    1086
15407      18000      Dealer    Petrol            Manual    17.50    1373
15408      67000      Dealer    Diesel            Manual    21.14    1498
15409    3800000      Dealer    Diesel            Manual    16.00    2179
15410      13000      Dealer    Petrol         Automatic    18.00    1497

       max_power  seats    price
0          46.30      5   120000
1          82.00      5   550000
2          80.00      5   215000
3          67.10      5   226000
4          98.59      5   570000
...          ...    ...      ...
15406      68.05      5   250000
15407      91.10      7   925000
15408     103.52      5   425000
15409     140.00      7  1225000
15410     117.60      5  1200000

[15411 rows x 14 columns]

- **Column/Row Selection**

In [19]:
df ['brand'] 	# single column

0          Maruti
1         Hyundai
2         Hyundai
3          Maruti
4            Ford
           ...
15406     Hyundai
15407      Maruti
15408       Skoda
15409    Mahindra
15410       Honda
Name: brand, Length: 15411, dtype: object

In [20]:
df [['brand' , 'price']] 	# multiple columns

          brand    price
0        Maruti   120000
1       Hyundai   550000
2       Hyundai   215000
3        Maruti   226000
4          Ford   570000
...         ...      ...
15406   Hyundai   250000
15407    Maruti   925000
15408     Skoda   425000
15409  Mahindra  1225000
15410     Honda  1200000

[15411 rows x 2 columns]

In [21]:
df.iloc[0] 	# first line

Unnamed: 0                     0
car_name             Maruti Alto
brand                     Maruti
model                       Alto
vehicle_age                    9
km_driven                 120000
seller_type           Individual
fuel_type                 Petrol
transmission_type         Manual
mileage                     19.7
engine                       796
max_power                   46.3
seats                          5
price                     120000
Name: 0, dtype: object

In [22]:
df.iloc[0:5] 	# lines 0 to 4

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [24]:
df.loc [df['price'] > 10000] 	# conditional filtering

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

- **Creating and Deleting Columns**

In [27]:
df['km_per_year'] = df['km_driven'] / df['vehicle_age'].replace(0, pd.NA)

pd.reset_option('display.max_columns') # reset display option in default mode
print(df)

RecursionError: maximum recursion depth exceeded in comparison

In [30]:
df.drop ('km_per_year' , axis= 1 , inplace = True) 
# removes the column named 'km_per_year' from the DataFrame df by specifying 
# axis=1 to indicate a column operation, and inplace=True to apply the change 
# directly without reassigning the DataFrame.

print(df)

KeyError: "['km_per_year'] not found in axis"

- **Display the row with the minimum price**

In [28]:
df[df['price'] == df['price'].min()]

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price
7607,9731,Maruti Wagon R,Maruti,Wagon R,21,80000,Individual,Petrol,Manual,18.9,998,67.1,5,40000

- **Sorting values**

In [29]:
df.sort_values (by = 'price' , ascending = False)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price
3799,4845,Ferrari GTC4Lusso,Ferrari,GTC4Lusso,2,3800,Dealer,Petrol,Automatic,4.00,3855,601.0,4,39500000
10969,13944,Rolls-Royce Ghost,Rolls-Royce,Ghost,4,5000,Individual,Petrol,Automatic,10.20,6592,563.0,4,24200000
1172,1508,Bentley Continental,Bentley,Continental,9,9000,Dealer,Petrol,Automatic,9.50,5998,626.0,4,14500000
9722,12456,Mercedes-Benz S-Class,Mercedes-Benz,S-Class,3,4000,Dealer,Petrol,Automatic,7.81,4663,459.0,4,13000000
9364,12023,Porsche Cayenne,Porsche,Cayenne,4,24000,Dealer,Petrol,Automatic,12.50,3604,440.0,5,11100000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3787,4831,Maruti Alto,Maruti,Alto,19,120000,Individual,Petrol,Manual,18.90,1061,47.0,5,50000
7361,9413,Honda City,Honda,City,19,110000,Individual,Petrol,Manual,13.00,1493,100.0,5,50000
12298,15593,Maruti Wagon R,Maruti,Wagon R,17,50000,Individual,Petrol,Manual,18.90,998,67.1,5,50000
13676,17349,Maruti Alto,Maruti,Alto,17,110000,Individual,Petrol,Manual,19.70,796,46.3,5,45000
7607,9731,Maruti Wagon R,Maruti,Wagon R,21,80000,Individual,Petrol,Manual,18.90,998,67.1,5,40000

# **🧪 Workshop :** 
- **Upload a CSV file containing vehicle information**
- **Show columns, types, and dimensions**
- **Count unique values in a column (eg fuel)**
- **Create a calculated column ( price_per_kg )**
- **Sort cars by descending price and extract the first 10**

In [31]:
import pandas as pd

df = pd.read_csv("cars.csv")

In [32]:
print("Columns:\n", df.columns)

print("\nData Types:\n", df.dtypes)

print("\nShape (rows, columns):", df.shape)

Columns:
 Index(['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
       'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
       'max_power', 'seats', 'price'],
      dtype='object')

Data Types:
 Unnamed: 0             int64
car_name              object
brand                 object
model                 object
vehicle_age            int64
km_driven              int64
seller_type           object
fuel_type             object
transmission_type     object
mileage              float64
engine                 int64
max_power            float64
seats                  int64
price                  int64
dtype: object

Shape (rows, columns): (15411, 14)

In [36]:
print("Number of unique fuel types:", df['fuel_type'].nunique())

print("\nFuel distribution:")
print(df['fuel_type'].value_counts())

Number of unique fuel types: 5

Fuel distribution:
Petrol      7643
Diesel      7419
CNG          301
LPG           44
Electric       4
Name: fuel_type, dtype: int64

In [39]:
import numpy as np

df['engine'] = df['engine'].replace(0, np.nan)
df['price_per_kg'] = df['price'] / df['engine']

top10 = df.sort_values(by='price', ascending=False).head(10)

print(top10[['car_name', 'brand', 'price']])

                    car_name          brand     price
3799       Ferrari GTC4Lusso        Ferrari  39500000
10969      Rolls-Royce Ghost    Rolls-Royce  24200000
1172     Bentley Continental        Bentley  14500000
9722   Mercedes-Benz S-Class  Mercedes-Benz  13000000
9364         Porsche Cayenne        Porsche  11100000
10989  Mercedes-Benz S-Class  Mercedes-Benz  11000000
1888   Mercedes-Benz S-Class  Mercedes-Benz  11000000
11000       Land Rover Rover     Land Rover   9200000
8439                   BMW 7            BMW   8500000
3096                   BMW 7            BMW   8500000